readonly DEFAULT_UBUNTU_VERSION=23.04
export UBUNTU_VERSION=${UBUNTU_VERSION:-$DEFAULT_UBUNTU_VERSION}

readonly DEFAULT_DPDK_VERSION=23.11
export DPDK_VERSION=${DPDK_VERSION:-$DEFAULT_DPDK_VERSION}

export IMAGE_NAME=docker.io/eyonggu/dpdk
